# Generated by Django 5.0.10 on 2026-02-23 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cycle_length_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='20-45 (tylko dla kobiet)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cycle_start_date',
            field=models.DateField(blank=True, help_text='Data początku ostatniego cyklu (YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enabled_alerts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('unspecified', 'Nie podano'), ('female', 'Kobieta'), ('male', 'Mężczyzna'), ('other', 'Inne')], default='unspecified', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DailyWellbeing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('stress_1_10', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exercise_1_10', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_wellbeing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'day'], name='portal_dail_user_id_d9833e_idx')],
                'unique_together': {('user', 'day')},
            },
        ),
    ]
