# Generated by Django 5.0.10 on 2026-03-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_userprofile_wg_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='display_name',
        ),
    ]
