# Generated by Django 4.2.28 on 2026-03-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_streaks_note_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywellbeing',
            name='daily_note',
            field=models.TextField(blank=True, default='', help_text='Notatka dnia (max 500 znaków)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='evening_reminder',
            field=models.BooleanField(default=True, help_text='Wieczorne przypomnienie o logowaniu samopoczucia'),
        ),
    ]
